### ISSUE TITLE
UB on game start

### ISSUE THREAD

**Issue by matthiaskrgr** [dorkster/flare-engine-next#25]
compile with CXXFLAGS="-fsanitize=undefined -O0 -g3"
run with
UBSAN_OPTIONS=print_stacktrace=1 ./flare  
theres some UB showing up when flare launches:
````
INFO: No joysticks were found.
INFO: Using Render Device: SDLSoftwareRenderDevice (software, SDL 2)
/home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:573:43: runtime error: downcast of address 0x603000025600 which does not point to an object of type 'SDLSoftwareImage'
0x603000025600: note: object is of type 'Image'
 0a 00 00 57  f8 12 e6 00 00 00 00 00  00 b1 00 00 e0 60 00 00  00 00 00 00 be be be be  a0 49 01 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'Image'
    #0 0xaea71c in SDLSoftwareRenderDevice::freeImage(Image*) /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:573
    #1 0xaab80c in Image::~Image() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:34
    #2 0xad9ff5 in SDLSoftwareImage::~SDLSoftwareImage() /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:40
    #3 0xada039 in SDLSoftwareImage::~SDLSoftwareImage() /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:41
    #4 0xaabd57 in Image::unref() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:44
    #5 0xaac571 in Sprite::~Sprite() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:81
    #6 0xb14aeb in SDLFontEngine::renderInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, Color const&) /home/matthias/vcs/github/flare-engine-next/src/SDLFontEngine.cpp:217
    #7 0x693eaf in FontEngine::render(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, int, Color const&) /home/matthias/vcs/github/flare-engine-next/src/FontEngine.cpp:145
    #8 0x695a5c in FontEngine::renderShadowed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, int, Color const&) /home/matthias/vcs/github/flare-engine-next/src/FontEngine.cpp:188
    #9 0xb9166a in WidgetLabel::recacheTextSprite() /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:266
    #10 0xb8ceb4 in WidgetLabel::set(int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Color const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:147
    #11 0xb8bd46 in WidgetLabel::set(int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Color const&) /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:106
    #12 0xb7eea3 in WidgetButton::refresh() /home/matthias/vcs/github/flare-engine-next/src/WidgetButton.cpp:169
    #13 0x72b100 in GameStateTitle::GameStateTitle() /home/matthias/vcs/github/flare-engine-next/src/GameStateTitle.cpp:106
    #14 0x7c1c60 in GameSwitcher::GameSwitcher() /home/matthias/vcs/github/flare-engine-next/src/GameSwitcher.cpp:54
    #15 0xbfafc1 in init /home/matthias/vcs/github/flare-engine-next/src/main.cpp:138
    #16 0xbfda6d in main /home/matthias/vcs/github/flare-engine-next/src/main.cpp:340
    #17 0x7f01b11f1400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #18 0x527b29 in _start (/home/matthias/vcs/github/flare-engine-next/build/flare+0x527b29)

/home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:573:46: runtime error: member access within address 0x603000025600 which does not point to an object of type 'SDLSoftwareImage'
0x603000025600: note: object is of type 'Image'
 0a 00 00 57  f8 12 e6 00 00 00 00 00  00 b1 00 00 e0 60 00 00  00 00 00 00 be be be be  a0 49 01 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'Image'
    #0 0xaea7d9 in SDLSoftwareRenderDevice::freeImage(Image*) /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:573
    #1 0xaab80c in Image::~Image() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:34
    #2 0xad9ff5 in SDLSoftwareImage::~SDLSoftwareImage() /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:40
    #3 0xada039 in SDLSoftwareImage::~SDLSoftwareImage() /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:41
    #4 0xaabd57 in Image::unref() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:44
    #5 0xaac571 in Sprite::~Sprite() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:81
    #6 0xb14aeb in SDLFontEngine::renderInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, Color const&) /home/matthias/vcs/github/flare-engine-next/src/SDLFontEngine.cpp:217
    #7 0x693eaf in FontEngine::render(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, int, Color const&) /home/matthias/vcs/github/flare-engine-next/src/FontEngine.cpp:145
    #8 0x695a5c in FontEngine::renderShadowed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, int, Color const&) /home/matthias/vcs/github/flare-engine-next/src/FontEngine.cpp:188
    #9 0xb9166a in WidgetLabel::recacheTextSprite() /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:266
    #10 0xb8ceb4 in WidgetLabel::set(int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Color const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:147
    #11 0xb8bd46 in WidgetLabel::set(int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Color const&) /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:106
    #12 0xb7eea3 in WidgetButton::refresh() /home/matthias/vcs/github/flare-engine-next/src/WidgetButton.cpp:169
    #13 0x72b100 in GameStateTitle::GameStateTitle() /home/matthias/vcs/github/flare-engine-next/src/GameStateTitle.cpp:106
    #14 0x7c1c60 in GameSwitcher::GameSwitcher() /home/matthias/vcs/github/flare-engine-next/src/GameSwitcher.cpp:54
    #15 0xbfafc1 in init /home/matthias/vcs/github/flare-engine-next/src/main.cpp:138
    #16 0xbfda6d in main /home/matthias/vcs/github/flare-engine-next/src/main.cpp:340
    #17 0x7f01b11f1400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #18 0x527b29 in _start (/home/matthias/vcs/github/flare-engine-next/build/flare+0x527b29)

/home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:574:56: runtime error: downcast of address 0x603000025600 which does not point to an object of type 'SDLSoftwareImage'
0x603000025600: note: object is of type 'Image'
 0a 00 00 57  f8 12 e6 00 00 00 00 00  00 b1 00 00 e0 60 00 00  00 00 00 00 be be be be  a0 49 01 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'Image'
    #0 0xaea8fb in SDLSoftwareRenderDevice::freeImage(Image*) /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:574
    #1 0xaab80c in Image::~Image() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:34
    #2 0xad9ff5 in SDLSoftwareImage::~SDLSoftwareImage() /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:40
    #3 0xada039 in SDLSoftwareImage::~SDLSoftwareImage() /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:41
    #4 0xaabd57 in Image::unref() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:44
    #5 0xaac571 in Sprite::~Sprite() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:81
    #6 0xb14aeb in SDLFontEngine::renderInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, Color const&) /home/matthias/vcs/github/flare-engine-next/src/SDLFontEngine.cpp:217
    #7 0x693eaf in FontEngine::render(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, int, Color const&) /home/matthias/vcs/github/flare-engine-next/src/FontEngine.cpp:145
    #8 0x695a5c in FontEngine::renderShadowed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, int, Color const&) /home/matthias/vcs/github/flare-engine-next/src/FontEngine.cpp:188
    #9 0xb9166a in WidgetLabel::recacheTextSprite() /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:266
    #10 0xb8ceb4 in WidgetLabel::set(int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Color const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:147
    #11 0xb8bd46 in WidgetLabel::set(int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Color const&) /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:106
    #12 0xb7eea3 in WidgetButton::refresh() /home/matthias/vcs/github/flare-engine-next/src/WidgetButton.cpp:169
    #13 0x72b100 in GameStateTitle::GameStateTitle() /home/matthias/vcs/github/flare-engine-next/src/GameStateTitle.cpp:106
    #14 0x7c1c60 in GameSwitcher::GameSwitcher() /home/matthias/vcs/github/flare-engine-next/src/GameSwitcher.cpp:54
    #15 0xbfafc1 in init /home/matthias/vcs/github/flare-engine-next/src/main.cpp:138
    #16 0xbfda6d in main /home/matthias/vcs/github/flare-engine-next/src/main.cpp:340
    #17 0x7f01b11f1400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #18 0x527b29 in _start (/home/matthias/vcs/github/flare-engine-next/build/flare+0x527b29)

/home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:574:59: runtime error: member access within address 0x603000025600 which does not point to an object of type 'SDLSoftwareImage'
0x603000025600: note: object is of type 'Image'
 0a 00 00 57  f8 12 e6 00 00 00 00 00  00 b1 00 00 e0 60 00 00  00 00 00 00 be be be be  a0 49 01 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'Image'
    #0 0xaea9b8 in SDLSoftwareRenderDevice::freeImage(Image*) /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:574
    #1 0xaab80c in Image::~Image() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:34
    #2 0xad9ff5 in SDLSoftwareImage::~SDLSoftwareImage() /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:40
    #3 0xada039 in SDLSoftwareImage::~SDLSoftwareImage() /home/matthias/vcs/github/flare-engine-next/src/SDLSoftwareRenderDevice.cpp:41
    #4 0xaabd57 in Image::unref() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:44
    #5 0xaac571 in Sprite::~Sprite() /home/matthias/vcs/github/flare-engine-next/src/RenderDevice.cpp:81
    #6 0xb14aeb in SDLFontEngine::renderInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, Color const&) /home/matthias/vcs/github/flare-engine-next/src/SDLFontEngine.cpp:217
    #7 0x693eaf in FontEngine::render(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, int, Color const&) /home/matthias/vcs/github/flare-engine-next/src/FontEngine.cpp:145
    #8 0x695a5c in FontEngine::renderShadowed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, Image*, int, Color const&) /home/matthias/vcs/github/flare-engine-next/src/FontEngine.cpp:188
    #9 0xb9166a in WidgetLabel::recacheTextSprite() /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:266
    #10 0xb8ceb4 in WidgetLabel::set(int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Color const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:147
    #11 0xb8bd46 in WidgetLabel::set(int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Color const&) /home/matthias/vcs/github/flare-engine-next/src/WidgetLabel.cpp:106
    #12 0xb7eea3 in WidgetButton::refresh() /home/matthias/vcs/github/flare-engine-next/src/WidgetButton.cpp:169
    #13 0x72b100 in GameStateTitle::GameStateTitle() /home/matthias/vcs/github/flare-engine-next/src/GameStateTitle.cpp:106
    #14 0x7c1c60 in GameSwitcher::GameSwitcher() /home/matthias/vcs/github/flare-engine-next/src/GameSwitcher.cpp:54
    #15 0xbfafc1 in init /home/matthias/vcs/github/flare-engine-next/src/main.cpp:138
    #16 0xbfda6d in main /home/matthias/vcs/github/flare-engine-next/src/main.cpp:340
    #17 0x7f01b11f1400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #18 0x527b29 in _start (/home/matthias/vcs/github/flare-engine-next/build/flare+0x527b29)
````

**Comment by dorkster** [comment]
Fix is now upstream: https://github.com/clintbellanger/flare-engine/commit/4e76bbbb2d8290e4012be4fff99f6b38fce330a2

**Comment by dorkster** [comment]
I've reverted the aforementioned "fix" as it resulted in Images not being freed at all.

**Comment by dorkster** [comment]
This is actually fixed now with the following commits:

- https://github.com/dorkster/flare-engine-next/commit/d2bea7344b87c11d801c098ab83a59911b99dfb8
- https://github.com/dorkster/flare-engine-next/commit/3a753415c77915d3b143ef88e3df3bd8e6280774
- https://github.com/dorkster/flare-engine-next/commit/6087422c3d68c139141797223990d4be721aee64

Also, an unrelated bit of undefined behavior was found and fixed here:

- https://github.com/dorkster/flare-engine-next/commit/fbab7ee162fea0b2609745a6967b690a653cd981
