### ISSUE TITLE
memleak GameStateLoad::readGameSlots() 

### ISSUE THREAD

**Issue by matthiaskrgr** [dorkster/flare-engine-next#26]
compile with CXXFLAGS="-fsanitize=address -O0 -g3 -fno-common -fno-omit-frame-pointer"

Play Game -> Select save -> exit title -> exit game
=>
````
Direct leak of 2592 byte(s) in 1 object(s) allocated from:
    #0 0x7fe147282e90 in operator new(unsigned long) (/lib64/libasan.so.3+0xc7e90)
    #1 0x5fc5b8 in GameStateLoad::readGameSlots() /home/matthias/vcs/github/flare-engine-next/src/GameStateLoad.cpp:317
    #2 0x5fb6e5 in GameStateLoad::GameStateLoad() /home/matthias/vcs/github/flare-engine-next/src/GameStateLoad.cpp:244
    #3 0x5f7879 in GameStateTitle::logic() /home/matthias/vcs/github/flare-engine-next/src/GameStateTitle.cpp:147
    #4 0x627e3b in GameSwitcher::logic() /home/matthias/vcs/github/flare-engine-next/src/GameSwitcher.cpp:192
    #5 0x7db7c9 in mainLoop /home/matthias/vcs/github/flare-engine-next/src/main.cpp:176
    #6 0x7dc9de in main /home/matthias/vcs/github/flare-engine-next/src/main.cpp:345
    #7 0x7fe1459be400 in __libc_start_main (/lib64/libc.so.6+0x20400)
````

**Comment by dorkster** [comment]
Fixed: https://github.com/clintbellanger/flare-engine/commit/54c0d0dccc3589284ce2250d367b0350992a6e59
